/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package rent_car;

import java.awt.Color;

/**
 *
 * @author gblan
 */
public class InicioSesion extends javax.swing.JFrame {

    /**
     * Creates new form InicioSesion
     */
    int xPos, yPos;

    public InicioSesion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        logoL = new javax.swing.JLabel();
        rightBg = new javax.swing.JLabel();
        exitButton = new javax.swing.JPanel();
        exitText = new javax.swing.JLabel();
        header = new javax.swing.JPanel();
        LoginText = new javax.swing.JLabel();
        passText = new javax.swing.JLabel();
        typeUser = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        userText = new javax.swing.JLabel();
        typePass = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        logButton = new javax.swing.JPanel();
        SignText = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logoL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rent/images/LogoRent (1).png"))); // NOI18N
        logoL.setText("jLabel3");
        bg.add(logoL, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 135, 122));

        rightBg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rent/images/fondoT (1).jpg"))); // NOI18N
        bg.add(rightBg, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 0, 440, 850));

        exitButton.setBackground(new java.awt.Color(255, 255, 255));

        exitText.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        exitText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitText.setText("X");
        exitText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitTextMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitTextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitTextMouseExited(evt);
            }
        });

        javax.swing.GroupLayout exitButtonLayout = new javax.swing.GroupLayout(exitButton);
        exitButton.setLayout(exitButtonLayout);
        exitButtonLayout.setHorizontalGroup(
            exitButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitText, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );
        exitButtonLayout.setVerticalGroup(
            exitButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitText, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        bg.add(exitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 40));

        header.setBackground(new java.awt.Color(255, 255, 255));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1280, Short.MAX_VALUE)
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        bg.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 40));

        LoginText.setFont(new java.awt.Font("Roboto Black", 1, 36)); // NOI18N
        LoginText.setText("INICIAR SESIÓN");
        bg.add(LoginText, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        passText.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        passText.setText("PASSWORD");
        bg.add(passText, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, -1, -1));

        typeUser.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        typeUser.setForeground(new java.awt.Color(153, 153, 153));
        typeUser.setText("Ingrese su username");
        typeUser.setToolTipText("");
        typeUser.setBorder(null);
        typeUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                typeUserMousePressed(evt);
            }
        });
        typeUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeUserActionPerformed(evt);
            }
        });
        bg.add(typeUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 430, 40));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bg.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 580, -1));

        userText.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        userText.setText("USERNAME");
        bg.add(userText, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));

        typePass.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        typePass.setForeground(new java.awt.Color(153, 153, 153));
        typePass.setText("**********");
        typePass.setBorder(null);
        typePass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                typePassMousePressed(evt);
            }
        });
        bg.add(typePass, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, 420, 40));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bg.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, 580, -1));

        logButton.setBackground(new java.awt.Color(0, 88, 111));

        SignText.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        SignText.setForeground(new java.awt.Color(255, 255, 255));
        SignText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SignText.setText("SIGN IN");
        SignText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SignTextMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SignTextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SignTextMouseExited(evt);
            }
        });

        javax.swing.GroupLayout logButtonLayout = new javax.swing.GroupLayout(logButton);
        logButton.setLayout(logButtonLayout);
        logButtonLayout.setHorizontalGroup(
            logButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SignText, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
        );
        logButtonLayout.setVerticalGroup(
            logButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SignText, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        bg.add(logButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 630, 240, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void typeUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typeUserActionPerformed

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        // TODO add your handling code here:
        xPos = evt.getX();
        yPos = evt.getY();

    }//GEN-LAST:event_headerMousePressed

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xPos, y - yPos);
    }//GEN-LAST:event_headerMouseDragged

    private void exitTextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTextMouseEntered
        // TODO add your handling code here:
        exitButton.setBackground(Color.red);
        exitText.setForeground(Color.white);
    }//GEN-LAST:event_exitTextMouseEntered

    private void exitTextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTextMouseExited
        // TODO add your handling code here:
        exitButton.setBackground(Color.white);
        exitText.setForeground(Color.black);
    }//GEN-LAST:event_exitTextMouseExited

    private void exitTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTextMouseClicked
        // TODO add your handling code here:
        System.exit(0);

    }//GEN-LAST:event_exitTextMouseClicked

    private void typeUserMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_typeUserMousePressed
        // TODO add your handling code here:
        if (typeUser.getText().equals("Ingrese su username")) {
            typeUser.setText("");
            typeUser.setForeground(Color.black);
        }
        if (String.valueOf(typePass.getPassword()).isEmpty()) {
            typePass.setText("**********");
            typePass.setForeground(Color.gray);
        }
    }//GEN-LAST:event_typeUserMousePressed

    private void typePassMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_typePassMousePressed
        if (typeUser.getText().isEmpty()) {
            typeUser.setText("Ingrese su username");
            typeUser.setForeground(Color.gray);
        }
        if (String.valueOf(typePass.getPassword()).equals("**********")) {
            typePass.setText("");
            typePass.setForeground(Color.black);
        }
    }//GEN-LAST:event_typePassMousePressed

    private void SignTextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignTextMouseEntered
        logButton.setBackground(new Color(0,134,168));
    }//GEN-LAST:event_SignTextMouseEntered

    private void SignTextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignTextMouseExited
        logButton.setBackground(new  Color (0,88,111));
    }//GEN-LAST:event_SignTextMouseExited

    private void SignTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignTextMouseClicked
        // Falta por definir
  
        
    }//GEN-LAST:event_SignTextMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicioSesion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LoginText;
    private javax.swing.JLabel SignText;
    private javax.swing.JPanel bg;
    private javax.swing.JPanel exitButton;
    private javax.swing.JLabel exitText;
    private javax.swing.JPanel header;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel logButton;
    private javax.swing.JLabel logoL;
    private javax.swing.JLabel passText;
    private javax.swing.JLabel rightBg;
    private javax.swing.JPasswordField typePass;
    private javax.swing.JTextField typeUser;
    private javax.swing.JLabel userText;
    // End of variables declaration//GEN-END:variables
}
