/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Interfaces;

/**
 *
 * @author gblan
 */
public class Clientes extends javax.swing.JInternalFrame {

    /**
     * Creates new form Clientes
     */
    public Clientes() {
        this.setSize(910, 690);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tittle = new javax.swing.JLabel();
        nameText = new javax.swing.JLabel();
        typeName = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        idText = new javax.swing.JLabel();
        typeId = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        birthText = new javax.swing.JLabel();
        typeBirth = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        emailText = new javax.swing.JLabel();
        typeEmail = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        lvText = new javax.swing.JLabel();
        lvOptions = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        addBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(null);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header.setBackground(new java.awt.Color(0, 78, 106));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Clientes");

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(761, Short.MAX_VALUE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        bg.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 40));

        tittle.setFont(new java.awt.Font("Roboto Black", 1, 36)); // NOI18N
        tittle.setText("Registro de Clientes");
        bg.add(tittle, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, -1, -1));

        nameText.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        nameText.setText("Nombre Completo:");
        bg.add(nameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, 20));

        typeName.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        typeName.setForeground(new java.awt.Color(153, 153, 153));
        typeName.setText("Ingrese el nombre completo del cliente");
        typeName.setBorder(null);
        typeName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeNameActionPerformed(evt);
            }
        });
        bg.add(typeName, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 240, -1));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        bg.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 260, 10));

        idText.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        idText.setText("Número de Cédula:");
        bg.add(idText, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        typeId.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        typeId.setForeground(new java.awt.Color(153, 153, 153));
        typeId.setText("Ingrese el ID card del cliente");
        typeId.setBorder(null);
        typeId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeIdActionPerformed(evt);
            }
        });
        bg.add(typeId, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 260, 30));

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        bg.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 260, 10));

        birthText.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        birthText.setText("Fecha de Nacimiento:");
        bg.add(birthText, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        typeBirth.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        typeBirth.setForeground(new java.awt.Color(153, 153, 153));
        typeBirth.setText("Ingrese la fecha de nacimiento");
        typeBirth.setToolTipText("");
        typeBirth.setBorder(null);
        typeBirth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeBirthActionPerformed(evt);
            }
        });
        bg.add(typeBirth, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 250, -1));

        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        bg.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 260, 10));

        emailText.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        emailText.setText("Correo Electrónico:");
        bg.add(emailText, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        typeEmail.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        typeEmail.setForeground(new java.awt.Color(153, 153, 153));
        typeEmail.setText("example@gmail.com");
        typeEmail.setBorder(null);
        bg.add(typeEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 270, -1));

        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));
        bg.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 250, 10));

        lvText.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        lvText.setText("Categoría: ");
        bg.add(lvText, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, -1));

        lvOptions.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bronce", "Plata", "Oro", "Zafiro" }));
        lvOptions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lvOptionsActionPerformed(evt);
            }
        });
        bg.add(lvOptions, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, 260, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nombre", "ID Card", "Fecha de Nacimiento", "Correo Electrónico", "Categoría"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        bg.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 840, 330));

        addBtn.setText("Agregar Nuevo Cliente");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });
        bg.add(addBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 130, 270, 50));

        updateBtn.setText("Modificar Cliente");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });
        bg.add(updateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 200, 270, 50));

        deleteBtn.setText("Eliminar Cliente");
        bg.add(deleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 270, 270, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void typeNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typeNameActionPerformed

    private void typeIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typeIdActionPerformed

    private void typeBirthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeBirthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typeBirthActionPerformed

    private void lvOptionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lvOptionsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lvOptionsActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JPanel bg;
    private javax.swing.JLabel birthText;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JLabel emailText;
    private javax.swing.JPanel header;
    private javax.swing.JLabel idText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> lvOptions;
    private javax.swing.JLabel lvText;
    private javax.swing.JLabel nameText;
    private javax.swing.JLabel tittle;
    private javax.swing.JTextField typeBirth;
    private javax.swing.JTextField typeEmail;
    private javax.swing.JTextField typeId;
    private javax.swing.JTextField typeName;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
