/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Interfaces;

import Rent_A_Car.*;
import java.awt.Color;

/**
 *
 * @author gblan
 */
public class Devoluciones extends javax.swing.JInternalFrame {

    /**
     * Creates new form Devoluciones
     */
    static ListaVehiculo listaVehiculo = new ListaVehiculo();
    static PilaAsignar asignados = new PilaAsignar();
    ListaDevolucion listaD = new ListaDevolucion();
    
    public Devoluciones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tittle = new javax.swing.JLabel();
        typeID = new javax.swing.JTextField();
        minPassText = new javax.swing.JLabel();
        typePlaca = new javax.swing.JTextField();
        marcaText = new javax.swing.JLabel();
        typeEstado = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        devolArea = new javax.swing.JTextArea();
        devolverBtn = new javax.swing.JButton();
        dayText = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header.setBackground(new java.awt.Color(0, 78, 106));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Devolucion");

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 40));

        tittle.setFont(new java.awt.Font("Roboto Black", 1, 36)); // NOI18N
        tittle.setText("Devolucion de Vehículo");
        jPanel1.add(tittle, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, -1, -1));

        typeID.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        typeID.setForeground(new java.awt.Color(153, 153, 153));
        typeID.setText("209780441");
        typeID.setBorder(null);
        typeID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                typeIDMousePressed(evt);
            }
        });
        typeID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeIDActionPerformed(evt);
            }
        });
        jPanel1.add(typeID, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 240, -1));

        minPassText.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        minPassText.setText("Placa del Vehiculo:");
        jPanel1.add(minPassText, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        typePlaca.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        typePlaca.setForeground(new java.awt.Color(153, 153, 153));
        typePlaca.setText("409425");
        typePlaca.setBorder(null);
        typePlaca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                typePlacaMousePressed(evt);
            }
        });
        jPanel1.add(typePlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 240, -1));

        marcaText.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        marcaText.setText("Estado del Vehiculo:");
        jPanel1.add(marcaText, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        typeEstado.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        typeEstado.setForeground(new java.awt.Color(153, 153, 153));
        typeEstado.setText("Rayones en la puerta derecha..");
        typeEstado.setBorder(null);
        typeEstado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                typeEstadoMousePressed(evt);
            }
        });
        jPanel1.add(typeEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 240, -1));

        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, 240, 10));

        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 240, 10));

        jSeparator7.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, 240, 10));

        devolArea.setEditable(false);
        devolArea.setColumns(20);
        devolArea.setRows(5);
        jScrollPane1.setViewportView(devolArea);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 890, 370));

        devolverBtn.setText("Realizar Devolucion");
        devolverBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                devolverBtnActionPerformed(evt);
            }
        });
        jPanel1.add(devolverBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 200, 200, 30));

        dayText.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        dayText.setText("Cedula de Cliente");
        jPanel1.add(dayText, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void typeIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typeIDActionPerformed

    private void devolverBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_devolverBtnActionPerformed
        // TODO add your handling code here:
        String placa = typePlaca.getText();
        String estado = typeEstado.getText();
        int id = Integer.parseInt(typeID.getText());
        listaD.add(new Devolucion (placa,estado,id));
        devolArea.setText(String.valueOf(listaD));
    }//GEN-LAST:event_devolverBtnActionPerformed

    private void typeIDMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_typeIDMousePressed
        // TODO add your handling code here:
        if (typeID.getText().equals("209780441")) {
            typeID.setText("");
            typeID.setForeground(Color.black);
        }

        if (typePlaca.getText().isEmpty()) {
            typePlaca.setText("409425");
            typePlaca.setForeground(Color.gray);
        }

        if (typeEstado.getText().isEmpty()) {
            typeEstado.setText("Rayones en la puerta derecha..");
            typeEstado.setForeground(Color.gray);
        }
    }//GEN-LAST:event_typeIDMousePressed

    private void typePlacaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_typePlacaMousePressed
        // TODO add your handling code here:
        if (typeID.getText().isEmpty()) {
            typeID.setText("209780441");
            typeID.setForeground(Color.gray);
        }

        if (typePlaca.getText().equals("409425")) {
            typePlaca.setText("");
            typePlaca.setForeground(Color.black);
        }

        if (typeEstado.getText().isEmpty()) {
            typeEstado.setText("Rayones en la puerta derecha..");
            typeEstado.setForeground(Color.gray);
        }
    }//GEN-LAST:event_typePlacaMousePressed

    private void typeEstadoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_typeEstadoMousePressed
        // TODO add your handling code here:
        if (typeID.getText().isEmpty()) {
            typeID.setText("209780441");
            typeID.setForeground(Color.gray);
        }

        if (typePlaca.getText().isEmpty()) {
            typePlaca.setText("409425");
            typePlaca.setForeground(Color.gray);
        }

        if (typeEstado.getText().equals("Rayones en la puerta derecha..")) {
            typeEstado.setText("");
            typeEstado.setForeground(Color.black);
        }
    }//GEN-LAST:event_typeEstadoMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dayText;
    private javax.swing.JTextArea devolArea;
    private javax.swing.JButton devolverBtn;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JLabel marcaText;
    private javax.swing.JLabel minPassText;
    private javax.swing.JLabel tittle;
    private javax.swing.JTextField typeEstado;
    private javax.swing.JTextField typeID;
    private javax.swing.JTextField typePlaca;
    // End of variables declaration//GEN-END:variables
}
